---

# TODO: Move other roles to a separate playbook as well
- name: Apply general roles
  hosts: all
  become: true
  roles:
    - unbound
    - kea_dhcp4_server

- name: Import monitoring playbook
  import_playbook: monitoring.yml

- name: Import containers playbook
  import_playbook: containers.yml
