---

- name: Apply all roles
  hosts: all
  become: true
  roles:
    - podman
    - unbound
    - prometheus_node_exporter
    - prometheus_unbound_exporter
    - prometheus_ts3exporter
    - prometheus
