---
interface_external: enp0s3
interface_internal: enp0s8

unbound_interfaces:
  - 127.0.0.1

unbound_remote_control: true
unbound_verbosity: 3
unbound_extended_statistics: true

kea_dhcp4_server_interfaces:
  - "{{ interface_internal }}"

kea_dhcp4_server_option_data:
  - name: domain-name-servers
    data: 192.168.0.1
  - name: domain-search
    data: 1.1.1.1

kea_dhcp4_server_subnets:
  - subnet: 192.168.10.0/24
    id: 1
    pools:
      - pool: 192.168.10.100-192.168.10.200
    option-data:
      - name: routers
        data: 192.168.0.1

prometheus_node_exporter_listen_address: :9100

caddy_config: |
  localhost {
      respond "Welcome to this dev server!"
  }

podman_volumes:
  - name: test-data

podman_pods:
  - name: redispod
    enabled: false
    ports:
      - 6379:6379
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target

podman_containers:
  - name: redis1234
    enabled: false
    image: docker.io/library/redis:latest
    pod: redispod.pod

  - name: redis
    enabled: false
    image: docker.io/library/redis:latest
