---

- name: Set name with resource type
  ansible.builtin.set_fact:
    resource_name: "{{ resource_type }}-{{ item.name }}"

- name: "Run tasks as {{ podman_user }}"
  become: true
  become_user: "{{ podman_user }}"
  block:
    - name: "Stop and disable service: {{ resource_name }}"
      ansible.builtin.systemd_service:
        name: "{{ resource_name }}"
        state: stopped
        enabled: false
        scope: user
      register: stop_service
      failed_when:
        - stop_service.failed == true
        - "'Could not find the requested service' not in stop_service.msg"

    - name: "Remove: {{ resource_name }}"
      containers.podman.podman_pod:
        name: "{{ item.name }}"
        state: absent

    - name: "Remove systemd unit file for: {{ resource_name }}"
      ansible.builtin.file:
        path: "{{ podman_user_home }}/.config/systemd/user/{{ resource_name }}.service"
        state: absent

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
