---


- name: "Run tasks as {{ podman_user }}"
  become: true
  become_user: "{{ podman_user }}"
  block:
    - name: "Stop and disable container service: {{ item.name }}"
      ansible.builtin.systemd_service:
        name: "container-{{ item.name }}"
        state: stopped
        enabled: false
        scope: user
      ignore_errors: true # TODO: replace with failed_when or something similar

    - name: "Remove container: {{ item.name }}"
      containers.podman.podman_container:
        name: "{{ item.name }}"
        state: absent

    - name: "Remove container image: {{ item.name }}"
      containers.podman.podman_image:
        name: "{{ item.name }}"
        state: absent

    - name: "Remove systemd unit file for container: {{ item.name }}"
      ansible.builtin.file:
        path: "{{ podman_user_home }}/.config/systemd/user/container-{{ item.name }}.service"
        state: absent

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
