---

# This feels a bit messy and there is probably a better way to do this. We need to omit many of the parameters if they are not defined
# in the podman_containers dict otherwise this module thinks something has changed every run and re-creates the container.
- name: "Create container: {{ item.name }}"
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    ports: "{{ item.ports if item.ports is defined else omit }}"
    volumes: "{{ item.volumes if item.volumes is defined else omit }}"
    command: "{{ item.command if item.command is defined else omit }}"
    env: "{{ item.env if item.env is defined else omit }}"
    secrets: "{{ item.secrets if item.secrets is defined else omit }}"
    user: "{{ item.user if item.user is defined else omit }}"
    userns: "{{ item.userns if item.userns is defined else omit }}"
    group_add: "{{ item.group_add if item.group_add is defined else omit }}"
    rm: true
    state: created
