---

- name: "Create pod: {{ item.name }}"
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_pod:
    name: "{{ item.name }}"
    state: created
    ports: "{{ item.ports if item.ports is defined else omit }}"
    userns: "{{ item.userns if item.userns is defined else omit }}"
