---

- name: "Run tasks as {{ podman_user }}"
  become: true
  become_user: "{{ podman_user }}"
  block:
    - name: "Generate systemd unit file for container: {{ item.name }}"
      containers.podman.podman_generate_systemd:
        name: "{{ item.name }}"
        new: true
        no_header: true
        restart_policy: always
        restart_sec: 10 # No effect right now - podman bug fixed in a more recent version
        dest: "{{ podman_user_home }}/.config/systemd/user"

      # TODO: Task above should trigger a restart on change

    - name: "Start container service: {{ item.name }}"
      ansible.builtin.systemd_service:
        name: "container-{{ item.name }}"
        state: started
        enabled: true
        scope: user
        daemon-reload: true
