#!/usr/sbin/nft -f

# Interfaces
define WAN_IF = eno1
define LAN_IF = eno2

# Local network
define LAN_NET = 192.168.0.0/24

# External address for source NAT
define WAN_IP = 37.xx.xx.xx # removed

# Flush current ruleset
flush ruleset

table inet firewall {
        chain input {
                type filter hook input priority 0; policy drop;

                ct state vmap { established : accept, related : accept, invalid : drop }

                iif { lo, $LAN_IF } accept

                ip protocol icmp limit rate 10/second accept
                ip6 nexthdr icmpv6 limit rate 10/second accept

                tcp dport { 22, 80, 443, 30033 } accept
                udp dport { 9987, 33434-33464 } accept
        }

        chain forward {
                type filter hook forward priority 0; policy drop;

                ct state vmap { established : accept, related : accept, invalid : drop }

                iif $LAN_IF accept
        }
}

table ip nat {
        chain postrouting {
                type nat hook postrouting priority 100; policy accept;

                ip saddr $LAN_NET oif $WAN_IF snat to $WAN_IP
        }
}
