---

podman_secrets:
  - name: ts3_serverquery_password
    data: "{{ vault_teamspeak3_serverquery_password }}"

podman_containers:
  # ts3exporter - Provides Prometheus metrics for a TeamSpeak 3 server
  - name: ts3exporter
    enabled: true
    image: docker.io/denniswitt/ts3exporter:1.1.4
    ports:
      - "127.0.0.1:9189:9189"
    env:
      REMOTE="192.168.0.1:10011"
    secrets:
      - ts3_serverquery_password,type=env,target=SERVERQUERY_PASSWORD

  # unbound_exporter - Prometheus metric exporter for the Unbound DNS resolver
  - name: unbound-exporter
    enabled: true
    image: docker.io/cyb3rjak3/unbound-exporter:0.4.6
    ports:
      - "127.0.0.1:9167:9167"
    command:
      - "-unbound.ca="
      - "-unbound.cert="
      - "-unbound.host=unix:///var/run/socket/unbound.ctl"
    volumes:
      - "/var/run/unbound.ctl:/var/run/socket/unbound.ctl:ro"
    group_add: keep-groups

  # Grafana - Data visualization platform
  - name: grafana
    enabled: true
    image: docker.io/grafana/grafana-oss:11.5.2
    ports:
      - "192.168.0.1:3000:3000"
    volumes:
      - "/home/podmanager/volumes/grafana:/var/lib/grafana"
    user: "472:472"
    userns: "keep-id:uid=472,gid=472"
    create_volume_dir: true
