---

prometheus_listen_address: :9090

prometheus_storage_tsdb_retention_time: 0s

prometheus_global_scrape_interval: 1m
prometheus_global_evaluation_interval: 1m

prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
