---

podman_user: podman
podman_user_home: /home/podman

podman_volumes: []
# Example:
# podman_volumes:
#   - name: test-data

podman_pods: []
# Example pod that starts on boot:
# podman_pods:
#   - name: redispod
#     enabled: true
#     ports:
#       - 6379:6379
#     quadlet_options:
#       - |
#         [Install]
#         WantedBy=default.target

podman_secrets: []
# Example:
# podman_secrets:
#   - name: database_password
#     data: "secretpassword"

podman_containers: []
# Basic example:
# podman_containers:
# - name: redis
#   enabled: true
#   image: docker.io/library/redis:latest
#
# Example with a container that belongs to a pod:
# podman_containers:
#   - name: redisinapod
#     enabled: true
#     image: docker.io/library/redis:latest
#     pod: redispod.pod
