global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["192.168.0.1:9100"]

  - job_name: "teamspeak"
    static_configs:
      - targets: ["192.168.0.1:9189"]

  - job_name: "unbound"
    static_configs:
      - targets: ["192.168.0.1:9167"]
